# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/harryculpan/src/CityState

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/harryculpan/src/CityState

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/harryculpan/src/CityState/CMakeFiles /Users/harryculpan/src/CityState/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/harryculpan/src/CityState/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CityState

# Build rule for target.
CityState: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CityState
.PHONY : CityState

# fast build rule for target.
CityState/fast:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/build
.PHONY : CityState/fast

src/Button.o: src/Button.cpp.o

.PHONY : src/Button.o

# target to build an object file
src/Button.cpp.o:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/Button.cpp.o
.PHONY : src/Button.cpp.o

src/Button.i: src/Button.cpp.i

.PHONY : src/Button.i

# target to preprocess a source file
src/Button.cpp.i:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/Button.cpp.i
.PHONY : src/Button.cpp.i

src/Button.s: src/Button.cpp.s

.PHONY : src/Button.s

# target to generate assembly for a file
src/Button.cpp.s:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/Button.cpp.s
.PHONY : src/Button.cpp.s

src/Component.o: src/Component.cpp.o

.PHONY : src/Component.o

# target to build an object file
src/Component.cpp.o:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/Component.cpp.o
.PHONY : src/Component.cpp.o

src/Component.i: src/Component.cpp.i

.PHONY : src/Component.i

# target to preprocess a source file
src/Component.cpp.i:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/Component.cpp.i
.PHONY : src/Component.cpp.i

src/Component.s: src/Component.cpp.s

.PHONY : src/Component.s

# target to generate assembly for a file
src/Component.cpp.s:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/Component.cpp.s
.PHONY : src/Component.cpp.s

src/FontManager.o: src/FontManager.cpp.o

.PHONY : src/FontManager.o

# target to build an object file
src/FontManager.cpp.o:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/FontManager.cpp.o
.PHONY : src/FontManager.cpp.o

src/FontManager.i: src/FontManager.cpp.i

.PHONY : src/FontManager.i

# target to preprocess a source file
src/FontManager.cpp.i:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/FontManager.cpp.i
.PHONY : src/FontManager.cpp.i

src/FontManager.s: src/FontManager.cpp.s

.PHONY : src/FontManager.s

# target to generate assembly for a file
src/FontManager.cpp.s:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/FontManager.cpp.s
.PHONY : src/FontManager.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/MainWindow.o: src/MainWindow.cpp.o

.PHONY : src/MainWindow.o

# target to build an object file
src/MainWindow.cpp.o:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/MainWindow.cpp.o
.PHONY : src/MainWindow.cpp.o

src/MainWindow.i: src/MainWindow.cpp.i

.PHONY : src/MainWindow.i

# target to preprocess a source file
src/MainWindow.cpp.i:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/MainWindow.cpp.i
.PHONY : src/MainWindow.cpp.i

src/MainWindow.s: src/MainWindow.cpp.s

.PHONY : src/MainWindow.s

# target to generate assembly for a file
src/MainWindow.cpp.s:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/MainWindow.cpp.s
.PHONY : src/MainWindow.cpp.s

src/TextOutput.o: src/TextOutput.cpp.o

.PHONY : src/TextOutput.o

# target to build an object file
src/TextOutput.cpp.o:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/TextOutput.cpp.o
.PHONY : src/TextOutput.cpp.o

src/TextOutput.i: src/TextOutput.cpp.i

.PHONY : src/TextOutput.i

# target to preprocess a source file
src/TextOutput.cpp.i:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/TextOutput.cpp.i
.PHONY : src/TextOutput.cpp.i

src/TextOutput.s: src/TextOutput.cpp.s

.PHONY : src/TextOutput.s

# target to generate assembly for a file
src/TextOutput.cpp.s:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/TextOutput.cpp.s
.PHONY : src/TextOutput.cpp.s

src/Window.o: src/Window.cpp.o

.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i

.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s

.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/terrain/BaseTerrain.o: src/terrain/BaseTerrain.cpp.o

.PHONY : src/terrain/BaseTerrain.o

# target to build an object file
src/terrain/BaseTerrain.cpp.o:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/terrain/BaseTerrain.cpp.o
.PHONY : src/terrain/BaseTerrain.cpp.o

src/terrain/BaseTerrain.i: src/terrain/BaseTerrain.cpp.i

.PHONY : src/terrain/BaseTerrain.i

# target to preprocess a source file
src/terrain/BaseTerrain.cpp.i:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/terrain/BaseTerrain.cpp.i
.PHONY : src/terrain/BaseTerrain.cpp.i

src/terrain/BaseTerrain.s: src/terrain/BaseTerrain.cpp.s

.PHONY : src/terrain/BaseTerrain.s

# target to generate assembly for a file
src/terrain/BaseTerrain.cpp.s:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/terrain/BaseTerrain.cpp.s
.PHONY : src/terrain/BaseTerrain.cpp.s

src/terrain/UnknownTerrain.o: src/terrain/UnknownTerrain.cpp.o

.PHONY : src/terrain/UnknownTerrain.o

# target to build an object file
src/terrain/UnknownTerrain.cpp.o:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/terrain/UnknownTerrain.cpp.o
.PHONY : src/terrain/UnknownTerrain.cpp.o

src/terrain/UnknownTerrain.i: src/terrain/UnknownTerrain.cpp.i

.PHONY : src/terrain/UnknownTerrain.i

# target to preprocess a source file
src/terrain/UnknownTerrain.cpp.i:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/terrain/UnknownTerrain.cpp.i
.PHONY : src/terrain/UnknownTerrain.cpp.i

src/terrain/UnknownTerrain.s: src/terrain/UnknownTerrain.cpp.s

.PHONY : src/terrain/UnknownTerrain.s

# target to generate assembly for a file
src/terrain/UnknownTerrain.cpp.s:
	$(MAKE) -f CMakeFiles/CityState.dir/build.make CMakeFiles/CityState.dir/src/terrain/UnknownTerrain.cpp.s
.PHONY : src/terrain/UnknownTerrain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CityState"
	@echo "... src/Button.o"
	@echo "... src/Button.i"
	@echo "... src/Button.s"
	@echo "... src/Component.o"
	@echo "... src/Component.i"
	@echo "... src/Component.s"
	@echo "... src/FontManager.o"
	@echo "... src/FontManager.i"
	@echo "... src/FontManager.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/MainWindow.o"
	@echo "... src/MainWindow.i"
	@echo "... src/MainWindow.s"
	@echo "... src/TextOutput.o"
	@echo "... src/TextOutput.i"
	@echo "... src/TextOutput.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/terrain/BaseTerrain.o"
	@echo "... src/terrain/BaseTerrain.i"
	@echo "... src/terrain/BaseTerrain.s"
	@echo "... src/terrain/UnknownTerrain.o"
	@echo "... src/terrain/UnknownTerrain.i"
	@echo "... src/terrain/UnknownTerrain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

